exports.Statuses = {
  NEW: 0,
  IN_PROGRESS: 1,
  WAITING_FOR_DELIVERY: 2,
  NO_DRIVER: 3,
  ON_DELIVERY: 4,
  CANCELED: 5,
  COMPLETED: 6,
  JACK_PENDING: 7,
  JACK_ACCEPTED: 8,
  JACK_ARRIVED_PICKUP: 9,
  JACK_OUT_FOR_DELIVERY: 10,
  JACK_ARRIVED_DROPFF: 11,
  JACK_CANCELED: 12
};